### ISSUE TITLE
concurrency: add SPI for context providers

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-sandbox#16]
In order for mp-concurrency to replace [Reactive Contexts](https://reactiverse.io/reactive-contexts/) which is currently used by RESTEasy to provide context propagation, we need to be able to define context providers via an SPI. Otherwise, context providers would be a fixed list and not support contexts that are external to MP/EE.

This can be as simple as defining a `ContextProvider` interface which supports:

- capturing a context
- setting a context
- restoring a context (in RESTEasy setting and restoring are different operations because the context is a stack with push/pop)

Where "the context" can be an opaque type that nobody outside of the context provider cares about (a type parameter would do).

Implementations of the `ContextProvider` can be listed with a `META-INF/services` file.

**Comment by njr-11** [comment]
To the best of my knowledge, the ThreadContextProvider SPI under pull #15 covers all of the above requirements and is conducive to context implementations that are stack-based as well as those that are not.  The doc additions under that pull also specify that the ServiceLoader (META-INF/services) is the way to plug in a third-party provider.  Can we close this issue if you are satisfied that everything is covered there?

**Comment by FroMage** [comment]
Yes, now that #15 has been merged, it appears to support this use-case. Thanks.
