### ISSUE TITLE
Create GraphQL README

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-sandbox#21]
Phillip Kruger is planning to move the proposal document into the README file (currently MD, but can be converted to AsciiDoc).
https://docs.google.com/document/d/1prwMGxgr0cI5yx4lrvMET5x6rD-CQ1y7XuS1PCegE4A/edit#

**Comment by phillip-kruger** [comment]
Done, see pull request #22

**Comment by phillip-kruger** [comment]
Redone, see pull request  #23
