### ISSUE TITLE
Add "deprecationReason" in ... #GraphQL

### ISSUE THREAD

**Issue by thejibz** [eclipse/microprofile-sandbox#31]
Add deprecationReason in
		@Type
		@InputType
		@Field
		@InputField

I think it's equally relevant on these annotations than on @Query.

**Comment by thejibz** [comment]
I have less experience in the Java world than the majority of you, so I don't always know what is a common practice across already existing and well-known APIs ! I will let the experts discuss ;)

**Comment by kaqqao** [comment]
If I'm not mistaken, none of the mentioned items can be deprecated. Only the output fields (i.e. queries/mutations/subscriptions) can be deprecated.
Also, there's no `@Field` (right?) as the queries _are_ fields.

**Comment by phillip-kruger** [comment]
I guess we can close this ? @andymc12
