### ISSUE TITLE
Annotation descriptions are inconsistent for LRA

### ISSUE THREAD

**Issue by nmcl** [eclipse/microprofile-sandbox#45]
With reference to https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/0009-LRA#java-annotations-for-lras

The doc spends over a page showing the @LRA annotation with examples but then only talks about how the other annotations, such as @Compensate, are used. For consistency and so someone can see precisely what annotations are being introduced, I suggest putting in as much detail for these other annotations as there is for @LRA.

**Comment by mmusgrov** [comment]
@nmcl we have created issue [#121](https://github.com/eclipse/microprofile-lra/issues/121) for this in the microprofile-lra repo. Do you mind if we close this one in preparation for removing LRA from the sandbox.

**Comment by mmusgrov** [comment]
Moved to https://github.com/eclipse/microprofile-lra/issues/121
